blueprint:
  name: HA Doorbell Notification
  description: >

    # [Home Assistant Doorbell Notification](https://github.com/WZYProjects/HA-Blueprints "WZYProjects Blueprints")

    ### Display a persistent notification in Home Assistant when someone rings the doorbell.

    Optional: If you select a camera, you will also get a snapshot in the notification.

    Snapshot files are created and stored in the folder "/config/www/doorbell"


    Version: 0.6

  author: w00zy
  source_url: https://github.com/WZYProjects/HA-Blueprints

  domain: automation

  input:
    notification_title:
      name: Title
      description: >
        **The title of your notification.**

        *Default: "Doorbell!"*
      default: "Doorbell!"
    notification_message:
      name: Message
      description: >
        **The message of your notification.**

        *Default: "Someone ringed the doorbell"*
      default: "Someone ringed the doorbell"
    doorbell_sensor:
      name: Doorbell Sensor
      description: >
        **The sensors associated with the doorbell ringing.**

        *Sensors that change the state to 'on' or 'ringing'*
      selector:
        entity:
          domain: 
          - sensor
          - binary_sensor
          multiple: true
    doorbell_camera:
      name: Doorbell Camera (Optional)
      description: >
        **Select a camera if you want to include a snapshot in the notification.**

        *doorbell_cam_timestamp.jpg*
      default: []
      selector:
        entity:
          domain: 
          - camera
    security_camera:
      name: Security Camera (Optional)
      description: >
        **Select a camera if you want to include a snapshot in the notification.**

        *security_cam_timestamp.jpg*
      default: []
      selector:
        entity:
          domain: 
          - camera

variables:
  notification_title: !input notification_title
  notification_message: !input notification_message
  doorbell_sensor: !input doorbell_sensor
  doorbell_camera: !input doorbell_camera
  security_camera: !input security_camera
  doorbell_snapshot: '/local/doorbell/doorbell_cam_{{ now().strftime("%Y-%m-%d_%H-%M") }}.jpg'
  security_snapshot: '/local/doorbell/security_cam_{{ now().strftime("%Y-%m-%d_%H-%M") }}.jpg'

trigger:
  - platform: state
    entity_id: !input doorbell_sensor

condition: 
  - condition: template
    value_template: "{{ trigger.to_state.state in ['on','ringing'] }}"

action:
  - service: camera.snapshot
    target:
      entity_id: !input doorbell_camera
    data_template:
      filename: '/config/www/doorbell/doorbell_cam_{{ now().strftime("%Y-%m-%d_%H-%M") }}.jpg'
  - service: camera.snapshot
    target:
      entity_id: !input security_camera
    data_template:
      filename: '/config/www/doorbell/security_cam_{{ now().strftime("%Y-%m-%d_%H-%M") }}.jpg'
  - service: persistent_notification.create
    data_template:
      title: '{{ notification_title }}'
      message: >
        {% if doorbell_camera and security_camera %}
          {{ notification_message }} <br>
          <img src="{{ security_snapshot }}">
          <img src="{{ doorbell_snapshot }}">
        {% elif doorbell_camera %}
          {{ notification_message }} <br>
          <img src="{{ doorbell_snapshot }}">
        {% elif security_camera %}
          {{ notification_message }} <br>
          <img src="{{ security_snapshot }}">
        {% else %}
          {{ notification_message }}
        {% endif %}
